apiVersion: v1
kind: Pod
metadata:
  name: bootcamp-pod
spec:
  volumes:
    - name: shared-data
      emptyDir: {}
  initContainers:
    - name: bootcamp-init
      image: busybox
      command:
        ["sh", "-c", "wget -O /usr/share/data/index.html https://wakapay.cash"]
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/data
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
