apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  volumes:
    - name: shared-data
      emptyDir: {}
  initContainers:
    - name: meminfo-container
      image: alpine
      restartPolicy: Always
      command:
        [
          "sh",
          "-c",
          "sleep 5; while true; do cat /proc/meminfo > /usr/share/data/index.html; sleep 10; done;",
        ]
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/data
  containers:
    - name: nginx-container
      image: nginx
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
