apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: first
  name: first
spec:
  nodeName: k8s-a
  containers:
    - name: nginx
      resources: {}
      image: nginx
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
